apiVersion: v1
kind: Service
metadata:
   name: jenkins-svc
   labels:
     app: jenkins-app
     type: jenkins-svc

spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  selector: 
      type: jenkins-pod
      app: jenkins-app