apiVersion: v1
kind: Pod
metadata:
   name: jenkins-pod
   labels:
      type: jenkins-pod
      app: jenkins-app
spec: 
  containers:
    - name: jenkins-app
      image: jenkins/jenkins:lts
      ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000