apiVersion: v1
kind: Pod
metadata:
   name: postgres-pod
   labels:
      type: postgres-pod
      app: voting-app
spec: 
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres