apiVersion: v1
kind: Service
metadata:
   name: db
   labels:
     app: voting-app
     type: postgres-svc

spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector: 
      type: postgres-pod
      app: voting-app