apiVersion: v1
kind: Service
metadata:
   name: redis
   labels:
     app: voting-app
     type: redis-svc

spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector: 
      type: redis-pod
      app: voting-app