apiVersion: v1
kind: Pod
metadata:
   name: result-pod
   labels:
      type: result-pod
      app: voting-app
spec: 
  containers:
    - name: result-app
      image: vsiraparapu/result-app
      ports:
        - containerPort: 80
  