apiVersion: v1
kind: Service
metadata:
   name: result-svc
   labels:
     app: voting-app
     type: result-svc

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
      
  selector: 
      type: result-pod
      app: voting-app