apiVersion: v1
kind: Service
metadata:
   name: voting-svc
   labels:
     app: voting-app
     type: voting-svc

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector: 
      type: voting-app-pod
      app: voting-app