apiVersion: v1
kind: Pod
metadata:
   name: worker-pod
   labels:
      type: worker-pod
      app: voting-app
spec: 
  containers:
    - name: workerapp
      image: vsiraparapu/worker-app
    