apiVersion: v1
kind: Service
metadata:
    name: sonar-svc
    labels: 
       app: sonar-app
       type: sonar-svc
spec: 
  type: LoadBalancer
  ports: 
     - port: 80
       targetPort: 9000
  selector: 
     app: sonar-app
     type: sonar-pod