apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-app-deploy
    labels:
        app: voting-app
        type: redis-app-deploy
spec:
  template:
      metadata:
        name: redis-pod
        labels:
            type: redis-pod
            app: voting-app
      spec: 
        containers:
          - name: redis
            image: redis
            ports:
              - containerPort: 6379
  replicas: 1
  selector:
      matchLabels:
            type: redis-pod
            app: voting-app