apiVersion: v1
kind: Service
metadata:
   name: voting-svc
   labels:
     app: voting-app
     type: voting-svc

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector: 
      type: voting-app-pod
      app: voting-app