apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myapp-relicaset
   labels:
      app: myapp
      type: frontend

spec:
  template:
     metadata:
       name: myapp
       labels: 
          app: myapp-pod
          type: frontend
     spec:
        containers:
          - image:  nginx
            name:   myapp
  replicas: 6     
  selector:
   matchLabels:
         type: frontend     